### ISSUE TITLE
Your web site has only one page

### ISSUE THREAD

**Issue by Shadrock** [Jianing79/jianing79#1]
Hi Jiang,
Your repo looks pretty good, but I wanted to check on the fact that you only have one page. Some others decided to get rid of their blog sections, but then they added a bit more design to the main page. Did you have any issues creating the blog according to the instructions for this exercise?

**Comment by Jianing79** [comment]
Dear Shadrock,

I am not really good at creating web page. I am sorry about that. So if it is not meet the qualifications, I can try to add more design on it.

Best,
Jianing


获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Shadrock Roberts <notifications@github.com>
发送时间: Monday, March 30, 2020 1:17:17 PM
收件人: Jianing79/jianing79 <jianing79@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [Jianing79/jianing79] Your web site has only one page (#1)


Hi Jiang,
Your repo looks pretty good, but I wanted to check on the fact that you only have one page. Some others decided to get rid of their blog sections, but then they added a bit more design to the main page. Did you have any issues creating the blog according to the instructions for this exercise?

―

**Comment by Shadrock** [comment]
It's okay: this repo is adequate. Just so you know, I don't expect perfect designs, just to see you try! In the future, don't hesitate to try and create new things, if they don't look like you would like. You can close this comment unless you want to discuss it further.

**Comment by Jianing79** [comment]
OK！ Thank you for your help and I will try my best to make new design in the future assignment.

Best,
Jianing

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Shadrock Roberts <notifications@github.com>
发送时间: Monday, March 30, 2020 2:00:45 PM
收件人: Jianing79/jianing79 <jianing79@noreply.github.com>
抄送: Li, Jianing <JianiLi@clarku.edu>; Comment <comment@noreply.github.com>
主题: Re: [Jianing79/jianing79] Your web site has only one page (#1)


It's okay: this repo is adequate. Just so you know, I don't expect perfect designs, just to see you try! In the future, don't hesitate to try and create new things, if they don't look like you would like. You can close this comment unless you want to discuss it further.

―
